server:
  address: 0.0.0.0
  port: 8080
spring:
  application:
    name: StudentManage
  freemarker:
    suffix: .html
    template-loader-path: classpath:/templates/
  thymeleaf:
    cache: false
    mode: HTML
  datasource:
    url: jdbc:mysql://localhost:3306/info?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
